const {readFileSync}=require('node:fs');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,setDoc,updateDoc,getDoc,getDocs,collection,deleteDoc,writeBatch,serverTimestamp,Timestamp}=require('firebase/firestore');
const assert=require('node:assert/strict');
(async()=>{
 const env=await initializeTestEnvironment({projectId:'demo-carbonautas',firestore:{host:'127.0.0.1',port:8085,rules:readFileSync('firestore.rules','utf8')}});
 const contexts={};for(const u of ['prof','alice','bob','new','wrong','unverified','egresso'])contexts[u]=env.authenticatedContext(u,{email:u+'@example.test',email_verified:u!=='unverified'}).firestore();
 const anon=env.unauthenticatedContext().firestore();let checks=0;
 const yes=async(label,p)=>{await assertSucceeds(p);checks++;console.log('OK',label)};
 const no=async(label,p)=>{await assertFails(p);checks++;console.log('OK bloqueado:',label)};
 try{
 await env.clearFirestore();
 await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();for(const id of ['prof','alice','bob','egresso']){await setDoc(doc(db,'rede_users',id),{role:id==='prof'?'coordinator':'student',memberId:id,email:id+'@example.test'});await setDoc(doc(db,'rede_members',id),{nome:id,nivel:id==='prof'?'coord':'mestrado',status:id==='egresso'?'egresso':'ativo'})}
 await setDoc(doc(db,'rede_members','newmember'),{nome:'Nova pessoa',nivel:'mestrado',status:'ativo'});
 await setDoc(doc(db,'rede_activities','act'),{ownerId:'alice',status:'aprovado',title:'Original',description:'Texto',updatedAt:Timestamp.fromMillis(1000)});
 await setDoc(doc(db,'rede_publicacoes','file'),{ownerUid:'prof',memberId:'alice',tipo:'arquivo',reviewFlow:false,collaboratorMemberIds:['bob'],url:'old',storagePath:'rede_publicacoes/prof/old.docx'});
 await setDoc(doc(db,'rede_feed_reactions','reaction'),{actorUid:'alice',type:'topizera'});
 for(const [id,email] of [['invite','new'],['unverified','unverified'],['expired','new']])await setDoc(doc(db,'rede_invites',id),{memberId:'newmember',nome:'Nova pessoa',email:email+'@example.test',expiresAt:Timestamp.fromMillis(id==='expired'?1:Date.now()+86400000),usedByUid:''});
 });
 await no('anônimo lê pessoas',getDocs(collection(anon,'rede_members')));
 await no('conta sem vínculo lista pessoas',getDocs(collection(contexts.new,'rede_members')));
 await no('conta sem vínculo lê perfil privado',getDoc(doc(contexts.new,'rede_members','alice')));
 await yes('aluno edita próprio projeto',updateDoc(doc(contexts.alice,'rede_members','alice'),{projetosAluno:[{title:'Meu projeto'}]}));
 await no('aluno edita projeto alheio',updateDoc(doc(contexts.bob,'rede_members','alice'),{projetosAluno:[]}));
 await no('aluno se promove',updateDoc(doc(contexts.alice,'rede_users','alice'),{role:'coordinator'}));
 await no('aluno mantém aprovação ao mudar texto',updateDoc(doc(contexts.alice,'rede_activities','act'),{title:'Outro'}));
 await yes('aluno ajusta seu aprovado e devolve à revisão',updateDoc(doc(contexts.alice,'rede_activities','act'),{title:'Revisado',status:'revisando'}));
 await no('aluno aprova',updateDoc(doc(contexts.alice,'rede_activities','act'),{status:'aprovado'}));
 await no('aluno disfarça aprovação com maiúscula',updateDoc(doc(contexts.alice,'rede_activities','act'),{status:'Aprovado'}));
 await no('aluno reprova',updateDoc(doc(contexts.alice,'rede_activities','act'),{status:'reprovado'}));
 await no('outro aluno edita',updateDoc(doc(contexts.bob,'rede_activities','act'),{title:'Alheio',status:'andamento'}));
 await no('aluno troca proprietário',updateDoc(doc(contexts.alice,'rede_activities','act'),{ownerId:'bob'}));
 await yes('professor aprova',updateDoc(doc(contexts.prof,'rede_activities','act'),{status:'aprovado'}));
 await yes('professor reprova',updateDoc(doc(contexts.prof,'rede_activities','act'),{status:'reprovado'}));
 await yes('aluno cria seu registro',setDoc(doc(contexts.alice,'rede_activities','newAct'),{ownerId:'alice',status:'andamento'}));
 await no('aluno cria aprovado',setDoc(doc(contexts.alice,'rede_activities','fakeApproval'),{ownerId:'alice',status:'aprovado'}));
 const before=(await getDoc(doc(contexts.alice,'rede_activities','act'))).data();const b=writeBatch(contexts.alice);
 b.set(doc(contexts.alice,'rede_activities','act','history','h1'),{before,actorUid:'alice',at:serverTimestamp()});b.update(doc(contexts.alice,'rede_activities','act'),{status:'revisando',title:'Novo'});
 await yes('edição + cópia anterior atômica',b.commit());
 await no('reescrever histórico',updateDoc(doc(contexts.alice,'rede_activities','act','history','h1'),{actorUid:'bob'}));
 await no('falsificar histórico',setDoc(doc(contexts.alice,'rede_activities','act','history','h2'),{before:{title:'Falso'},actorUid:'alice',at:serverTimestamp()}));
 await yes('dono lógico salva Office',updateDoc(doc(contexts.alice,'rede_publicacoes','file'),{url:'new',storagePath:'rede_publicacoes/alice/edit.docx',onlineEditVersion:2}));
 await yes('colaborador salva Office',updateDoc(doc(contexts.bob,'rede_publicacoes','file'),{url:'new2',storagePath:'rede_publicacoes/bob/edit.docx',onlineEditVersion:3}));
 await no('colaborador referencia objeto alheio',updateDoc(doc(contexts.bob,'rede_publicacoes','file'),{storagePath:'rede_publicacoes/prof/secret.docx'}));
 await no('colaborador muda autoria',updateDoc(doc(contexts.bob,'rede_publicacoes','file'),{ownerUid:'bob'}));
 await no('sequestrar reação',updateDoc(doc(contexts.bob,'rede_feed_reactions','reaction'),{actorUid:'bob'}));
 await yes('editar própria reação',updateDoc(doc(contexts.alice,'rede_feed_reactions','reaction'),{type:'linduuu'}));
 await no('egresso lê conteúdo',getDoc(doc(contexts.egresso,'rede_activities','act')));
 await no('outro email lê convite',getDoc(doc(contexts.wrong,'rede_invites','invite')));
 await no('email não confirmado lê convite',getDoc(doc(contexts.unverified,'rede_invites','unverified')));
 await yes('destinatário lê convite',getDoc(doc(contexts.new,'rede_invites','invite')));
 const claim=(db,code)=>{const x=writeBatch(db);x.set(doc(db,'rede_member_claims','newmember'),{uid:'new',memberId:'newmember',email:'new@example.test',registrationCode:code,createdAt:serverTimestamp()});x.set(doc(db,'rede_users','new'),{memberId:'newmember',nome:'Nova pessoa',email:'new@example.test',role:'student',createdAt:serverTimestamp()});x.update(doc(db,'rede_invites',code),{usedByUid:'new',usedAt:serverTimestamp()});return x.commit()};
 await no('convite expirado',claim(contexts.new,'expired'));
 await yes('autocadastro com convite pessoal',claim(contexts.new,'invite'));
 assert.equal((await getDoc(doc(contexts.new,'rede_users','new'))).data().memberId,'newmember');checks++;
 await no('reutilização do convite',claim(contexts.new,'invite'));
 console.log(`\n${checks} verificações de segurança passaram (emulador, nenhum dado real).`);
 }finally{await env.cleanup()}
})().catch(e=>{console.error(e);process.exitCode=1});
